######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 28 22:42:55 2008
######################################################################

TEMPLATE = app
TARGET = ikmtool 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_MAC_SDK=/Developer/SDKs/MacOSX10.5.sdk


CONFIG += qt
QT += sql
DESTDIR = ./

ICON = macosxicns.icns

# Input
HEADERS += mainwindow.h
FORMS += mainForm.ui
SOURCES += main.cpp mainwindow.cpp
