######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 28 22:42:55 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainForm.ui
SOURCES += main.cpp mainwindow.cpp
